export const LOAD_MEMBERS_SUCCESS = 'LOAD_MEMBERS_SUCCESS';
export const SAVED_MEMBER_SUCCESS = 'SAVED_MEMBER_SUCCESS';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const DELETE_MEMBER_SUCESS = 'DELETED_MEMBER_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_SUBGROUPS_SUCCESS = 'LOAD_SUBGROUPS_SUCCESS';